server {
    listen 8080;
    root /usr/share/nginx/html;
    server_tokens off;

    index index.html;

    location = /_health {
        access_log off;
        return 200 'OK';
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
