name: Build and test

permissions: {}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build_test_deploy:
    permissions:
      contents: write
    name: Build, test and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Set up Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version: 24.x
          cache: yarn

      - name: Install packages
        run: |
          yarn --immutable

      - name: Lint, test, and build
        run: |
          yarn lint
          yarn test
          yarn build
